### ISSUE TITLE
Constant git updates

### ISSUE THREAD

**Issue by dEhiN** [JacquesGariepy/out-of-code-insights#2]
I had add the `.out-of-code-insights` folder to my `.gitignore` file just because every annotation change would trigger a git change. This caused tools like _GitHub Pull Requests_ to keep highlighting the JSOn file as changed.

I work on multiple devices, so I would love to have my annotations file synced, but I don't want to be committing if all I've made are annotation changes and haven't changed any of the actual files themselves.

**Comment by JacquesGariepy** [comment]
Indeed, it is recommended to ignore this file if you are not working in a team. I will take note of adding an option in the settings to modify the location of the annotations file.
