### ISSUE TITLE
FR: Allow AI intergration to be disabled

### ISSUE THREAD

**Issue by tyler36** [JacquesGariepy/out-of-code-insights#5]
Is there a way to disable the AI intergration?

After install `1.0.7` I get popups for "OpenAI key is required for AI suggestions". 
If I change `"annotation.provider": "copilot"`, I get popups for Copilot key.

As I don't use either provider, I find the popups annoying. They occur evertime I load a new session.

What I would like to do is set `"annotation.provider": false` to disable the AI intergration completely. 
Not sure if there is a way to do this currently. None of the other options seems relevant, appologies if I overlook it.

Thank you for your consideration.

**Comment by dEhiN** [comment]
I came here to report the same thing. Here's a screenshot I took:

![image](https://github.com/user-attachments/assets/c09fdea4-1387-4610-87c6-ba69a562ff5b)

**Comment by JacquesGariepy** [comment]
I'll fix it in the next version. For now ignore the message.
